/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.domotica;

import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Orlando
 */
public class Musica extends javax.swing.JFrame {

    Reproductor r = null;

    public Musica() {

        r = new Reproductor();
        
        initComponents();
        this.setTitle("Reproductor");
        this.setLocationRelativeTo(null);
        
        try {
                    r.AbrirFichero("C:/Users/Public/Music/Sample Music/#Selfie (Original Mix).mp3");
                } catch (Exception ex) {
                    Logger.getLogger(Musica.class.getName()).log(Level.SEVERE, null, ex);
                }
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play_pause = new javax.swing.JToggleButton();
        anterior = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setSize(new java.awt.Dimension(280, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        play_pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Accesorios/play.png"))); // NOI18N
        play_pause.setContentAreaFilled(false);
        play_pause.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Accesorios/play.png"))); // NOI18N
        play_pause.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Accesorios/pause.png"))); // NOI18N
        play_pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play_pauseActionPerformed(evt);
            }
        });
        getContentPane().add(play_pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 80, 70));

        anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Accesorios/anterior.png"))); // NOI18N
        anterior.setContentAreaFilled(false);
        anterior.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Accesorios/anterior2.png"))); // NOI18N
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 88, 70));

        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Accesorios/siguiente.png"))); // NOI18N
        siguiente.setContentAreaFilled(false);
        siguiente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Accesorios/siguiente2.png"))); // NOI18N
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 80, 69));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Accesorios/reproductor 6.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void play_pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play_pauseActionPerformed
        
        play_pause.setSelected(!play);
        if (play == false) {
            
            //play_pause.setSelected(!play);
            play = true;
            if (sigue == 0) {
                sigue++;
                try {
                    //r.AbrirFichero("C:/Users/Public/Music/Sample Music/This Is What You Came For.mp3");
                    //r.AbrirFichero("C:/Users/Public/Music/Sample Music/#Selfie (Original Mix).mp3");
                    //r.AbrirFichero("C:/Users/Public/Music/Sample Music/01. Don't Let Me Down (Original Mix).mp3");
                    r.Play();
                    num++;
                } catch (Exception e) {
                }

            } else {//para que continue

                try {
                    r.Continuar();
                    play_pause.setSelected(play);
                } catch (Exception e) {
                }
                //sigue=0;
            }

        } else {
            play = false;
            try {
                r.Pausa();
            } catch (Exception e) {

            }

        }

    }//GEN-LAST:event_play_pauseActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed

        num++;
        play_pause.setSelected(true);
        //System.out.println(num);
        
        if(num==1){
            
            try {
                    r.AbrirFichero("C:/Users/Public/Music/Sample Music/#Selfie (Original Mix).mp3");
                    r.Play();
                    Fondo.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/Accesorios/reproductor 6.jpg")));

                } catch (Exception ex) {
                    Logger.getLogger(Musica.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(num);
        }
        
        if (num==2){
            
            try {
                    r.AbrirFichero("C:/Users/Public/Music/Sample Music/01. Don't Let Me Down (Original Mix).mp3");
                    r.Play();
                    Fondo.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/Accesorios/reproductor 1.jpg")));

                } catch (Exception ex) {
                    Logger.getLogger(Musica.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(num);
            
        }
        
        if (num==3){
            
            try {
                    r.AbrirFichero("C:/Users/Public/Music/Sample Music/Bailar (Original Mix).mp3");
                    r.Play();
                    Fondo.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/Accesorios/reproductor 4.jpg")));

                } catch (Exception ex) {
                    Logger.getLogger(Musica.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(num);
            
            
        }
        
        if (num==4){
            
            try {
                    r.AbrirFichero("C:/Users/Public/Music/Sample Music/4B - Hold Up (D-John Remix).mp3");
                    r.Play();
                    Fondo.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/Accesorios/reproductor 3.jpg")));

                } catch (Exception ex) {
                    Logger.getLogger(Musica.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(num);
            
            
        }
        
        if (num==5){
            
            try {
                    r.AbrirFichero("C:/Users/Public/Music/Sample Music/Do It Right Original Mix.mp3");
                    r.Play();
                    Fondo.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/Accesorios/reproductor 5.jpg")));

                } catch (Exception ex) {
                    Logger.getLogger(Musica.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(num);
                num=0;
            
        }
        
        
    }//GEN-LAST:event_siguienteActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        num--;
        
        play_pause.setSelected(true);
        
        if(num==1 || num<1){
            
            try {
                    r.AbrirFichero("C:/Users/Public/Music/Sample Music/#Selfie (Original Mix).mp3");
                    r.Play();
                    Fondo.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/Accesorios/reproductor 6.jpg")));

                } catch (Exception ex) {
                    Logger.getLogger(Musica.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(num);
                num=5;
        }
        
        if (num==2){
            
            try {
                    r.AbrirFichero("C:/Users/Public/Music/Sample Music/01. Don't Let Me Down (Original Mix).mp3");
                    r.Play();
                    Fondo.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/Accesorios/reproductor 1.jpg")));

                } catch (Exception ex) {
                    Logger.getLogger(Musica.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(num);
            
        }
        
        if (num==3){
            
            try {
                    r.AbrirFichero("C:/Users/Public/Music/Sample Music/Bailar (Original Mix).mp3");
                    r.Play();
                    Fondo.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/Accesorios/reproductor 4.jpg")));

                } catch (Exception ex) {
                    Logger.getLogger(Musica.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(num);
            
            
        }
        
        if (num==4){
            
            try {
                    r.AbrirFichero("C:/Users/Public/Music/Sample Music/4B - Hold Up (D-John Remix).mp3");
                    r.Play();
                    Fondo.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/Accesorios/reproductor 3.jpg")));

                } catch (Exception ex) {
                    Logger.getLogger(Musica.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(num);
            
            
        }
        
        if (num==5){
            
            try {
                    r.AbrirFichero("C:/Users/Public/Music/Sample Music/Do It Right Original Mix.mp3");
                    r.Play();
                    Fondo.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/Accesorios/reproductor 5.jpg")));

                } catch (Exception ex) {
                    Logger.getLogger(Musica.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(num);
                
            
        }
        
        
    }//GEN-LAST:event_anteriorActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("chao");
        
        //JOptionPane.showMessageDialog(null," Coloca un tiempo de ejecucion valido.","Error",JOptionPane.ERROR_MESSAGE);
        int n=JOptionPane.showConfirmDialog(null, "Seguro que desea salir del reproductor?." , "Advertencia" ,JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        System.out.println(n);

        if(n==0){
            try{
            r.Stop();
            }catch(Exception e){}
            dispose();
        }
        
        
        
        
    }//GEN-LAST:event_formWindowClosing
 
    
    public int num = 0;
    public int sigue = 0;

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Musica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Musica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Musica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Musica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Musica().setVisible(true);
            }
        });
    }

    public boolean play = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton anterior;
    private javax.swing.JToggleButton play_pause;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/logo musica.png")));
    }

    
}
