
package proyecto.domotica;

import java.applet.AudioClip;
import java.awt.Toolkit;
import java.awt.*;


public class Vista_Principal extends javax.swing.JFrame {

    Temperatura tem = new Temperatura();
    Ayuda help = new Ayuda();
    
    public Vista_Principal() {
        initComponents();
        
        this.setTitle("Domotic House");
        this.setLocationRelativeTo(null);
        //this.setResizable(false);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        Boton_Salir = new javax.swing.JButton();
        Boton_Sala = new javax.swing.JButton();
        Boton_Pasillo = new javax.swing.JButton();
        Boton_Baño = new javax.swing.JButton();
        Bton_Garage = new javax.swing.JButton();
        Boton_Porche = new javax.swing.JButton();
        Boton_Cuarto = new javax.swing.JButton();
        Boton_Cocina = new javax.swing.JButton();
        Temp_boton = new javax.swing.JToggleButton();
        Ayuda = new javax.swing.JButton();
        BotonPlanos = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(720, 520));

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen_principal/Arriba Dia.jpg"))); // NOI18N

        Boton_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Boton_Salir Nuevo 1.png"))); // NOI18N
        Boton_Salir.setToolTipText("Volver a la Portada");
        Boton_Salir.setContentAreaFilled(false);
        Boton_Salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Boton_Salir Nuevo 3.png"))); // NOI18N
        Boton_Salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Boton_Salir Nuevo 2.png"))); // NOI18N
        Boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalirActionPerformed(evt);
            }
        });

        Boton_Sala.setContentAreaFilled(false);
        Boton_Sala.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Boton Sala 2.png"))); // NOI18N
        Boton_Sala.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Boton Sala.png"))); // NOI18N
        Boton_Sala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalaActionPerformed(evt);
            }
        });

        Boton_Pasillo.setContentAreaFilled(false);
        Boton_Pasillo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botn Pasillo 2.png"))); // NOI18N
        Boton_Pasillo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Botn Pasillo.png"))); // NOI18N
        Boton_Pasillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PasilloActionPerformed(evt);
            }
        });

        Boton_Baño.setContentAreaFilled(false);
        Boton_Baño.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton baño 2.png"))); // NOI18N
        Boton_Baño.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton baño1.png"))); // NOI18N
        Boton_Baño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_BañoActionPerformed(evt);
            }
        });

        Bton_Garage.setContentAreaFilled(false);
        Bton_Garage.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton garage 2.png"))); // NOI18N
        Bton_Garage.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton garage 1.png"))); // NOI18N
        Bton_Garage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bton_GarageActionPerformed(evt);
            }
        });

        Boton_Porche.setContentAreaFilled(false);
        Boton_Porche.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Boton porche 2.png"))); // NOI18N
        Boton_Porche.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/porche boton 1.png"))); // NOI18N
        Boton_Porche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PorcheActionPerformed(evt);
            }
        });

        Boton_Cuarto.setContentAreaFilled(false);
        Boton_Cuarto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton Cuarto 2.png"))); // NOI18N
        Boton_Cuarto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Cuarto 1.png"))); // NOI18N
        Boton_Cuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CuartoActionPerformed(evt);
            }
        });

        Boton_Cocina.setContentAreaFilled(false);
        Boton_Cocina.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton cocina 2.png"))); // NOI18N
        Boton_Cocina.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton cocina 1.png"))); // NOI18N
        Boton_Cocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CocinaActionPerformed(evt);
            }
        });

        Temp_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton temperatura 1.png"))); // NOI18N
        Temp_boton.setToolTipText("Abrir/Cerrar control de Temperatura");
        Temp_boton.setContentAreaFilled(false);
        Temp_boton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton temperatura 2.png"))); // NOI18N
        Temp_boton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/boton temperatura 3.png"))); // NOI18N
        Temp_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Temp_botonActionPerformed(evt);
            }
        });

        Ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Boton ayuda 1.png"))); // NOI18N
        Ayuda.setToolTipText("Ayuda");
        Ayuda.setContentAreaFilled(false);
        Ayuda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Boton ayuda 2.png"))); // NOI18N
        Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaActionPerformed(evt);
            }
        });

        BotonPlanos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Boton_Planos 1.png"))); // NOI18N
        BotonPlanos.setToolTipText("Planos");
        BotonPlanos.setContentAreaFilled(false);
        BotonPlanos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Boton_Planos 2.png"))); // NOI18N
        BotonPlanos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Boton_Planos 3.png"))); // NOI18N
        BotonPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPlanosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(Boton_Sala, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Boton_Pasillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                        .addComponent(Boton_Baño, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Boton_Cuarto, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                                    .addComponent(Boton_Cocina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(Boton_Porche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(Temp_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonPlanos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addComponent(Bton_Garage, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                        .addComponent(Boton_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Boton_Sala, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                        .addComponent(Boton_Pasillo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Boton_Baño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Boton_Cuarto, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Boton_Cocina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(Boton_Porche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Bton_Garage, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonPlanos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Temp_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalirActionPerformed
        Portada_Main pm = new Portada_Main();
        pm.setVisible(true);
        Click.play();
        dispose();
        
        if(temp==true){
           temp=false;
           tem.dispose(); 
            
        }

    }//GEN-LAST:event_Boton_SalirActionPerformed

    private void Boton_SalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalaActionPerformed
        
        Click.play();
        Main_Sala obj = new Main_Sala();
        obj.setVisible(true);
        
        dispose();
        
        if(temp==true){
            
            tem.dispose();
        }
    }//GEN-LAST:event_Boton_SalaActionPerformed

    private void Boton_PasilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PasilloActionPerformed
        Click.play();
        Main_Pasillo obj = new Main_Pasillo();
        obj.setVisible(true);
        
        dispose();
        
        if(temp==true){
            
            tem.dispose();
        }
    }//GEN-LAST:event_Boton_PasilloActionPerformed

    private void Bton_GarageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bton_GarageActionPerformed
        
        Click.play();
        Garage_Arriba ga = new Garage_Arriba();
        ga.setVisible(true);
        dispose();
        Click.play();
        if(temp==true){
            
            tem.dispose();
        }
    }//GEN-LAST:event_Bton_GarageActionPerformed

    private void Boton_CocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_CocinaActionPerformed
        dispose();
        Click.play();
        Cocina co = new Cocina();
        
        co.setVisible(true);
        
        if(temp==true){
            
            tem.dispose();
        }
    }//GEN-LAST:event_Boton_CocinaActionPerformed

    private void Boton_CuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_CuartoActionPerformed
        Click.play();
        Cuarto cu= new Cuarto();
        cu.setVisible(true);
        
        dispose();
        
        if(temp==true){
            
            tem.dispose();
        }
    }//GEN-LAST:event_Boton_CuartoActionPerformed

    private void Boton_PorcheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PorcheActionPerformed
        Click.play();
        Porche po=new Porche();
        po.setVisible(true);
        dispose();
        Click.play();
        if(temp==true){
            
            tem.dispose();
        }
    }//GEN-LAST:event_Boton_PorcheActionPerformed

    private void Boton_BañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_BañoActionPerformed
        
        Click.play();
        BanoAfuera ba = new BanoAfuera();
        ba.setVisible(true);
        
        dispose();
        
        if(temp==true){
            
            tem.dispose();
        }
    }//GEN-LAST:event_Boton_BañoActionPerformed

    private void Temp_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Temp_botonActionPerformed
        Click.play();
        if(temp==false){
            
          temp=true;
            
            tem.setVisible(true);
            
        }else{
            
            temp=false;
            tem.dispose();
        }
        
        
    }//GEN-LAST:event_Temp_botonActionPerformed

    private void AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaActionPerformed
        Click.play();
        if (Help == false){
        
        Help=true;
        help.setVisible(true);
        
        }else{
            Help=false;
            help.dispose();
            
        }
    }//GEN-LAST:event_AyudaActionPerformed

    private void BotonPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPlanosActionPerformed
        Planos p = new Planos();
        Click.play();
        p.setVisible(true);
        
        dispose();
        
        if(temp==true){
            
            tem.dispose();
        }
    }//GEN-LAST:event_BotonPlanosActionPerformed

     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bano_interno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bano_interno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bano_interno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bano_interno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Principal().setVisible(true);
            }
        });
    }
    
  
    private boolean temp;// = false;
    private boolean Help;// = false;
    AudioClip Click = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Mouse.wav"));

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ayuda;
    private javax.swing.JToggleButton BotonPlanos;
    private javax.swing.JButton Boton_Baño;
    private javax.swing.JButton Boton_Cocina;
    private javax.swing.JButton Boton_Cuarto;
    private javax.swing.JButton Boton_Pasillo;
    private javax.swing.JButton Boton_Porche;
    private javax.swing.JButton Boton_Sala;
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JButton Bton_Garage;
    private javax.swing.JToggleButton Temp_boton;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo_icon.png")));
    }
}


